//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Pubs.Data
{
    public partial class employee
    {
        #region Primitive Properties
    
        public virtual string id
        {
            get;
            set;
        }
    
        public virtual string firstname
        {
            get;
            set;
        }
    
        public virtual string minit
        {
            get;
            set;
        }
    
        public virtual string lastname
        {
            get;
            set;
        }
    
        public virtual short jobid
        {
            get { return _jobid; }
            set
            {
                if (_jobid != value)
                {
                    if (job != null && job.id != value)
                    {
                        job = null;
                    }
                    _jobid = value;
                }
            }
        }
        private short _jobid;
    
        public virtual Nullable<byte> joblevel
        {
            get;
            set;
        }
    
        public virtual string publisherid
        {
            get { return _publisherid; }
            set
            {
                if (_publisherid != value)
                {
                    if (publisher != null && publisher.id != value)
                    {
                        publisher = null;
                    }
                    _publisherid = value;
                }
            }
        }
        private string _publisherid;
    
        public virtual System.DateTime hiredate
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual job job
        {
            get { return _job; }
            set
            {
                if (!ReferenceEquals(_job, value))
                {
                    var previousValue = _job;
                    _job = value;
                    Fixupjob(previousValue);
                }
            }
        }
        private job _job;
    
        public virtual publisher publisher
        {
            get { return _publisher; }
            set
            {
                if (!ReferenceEquals(_publisher, value))
                {
                    var previousValue = _publisher;
                    _publisher = value;
                    Fixuppublisher(previousValue);
                }
            }
        }
        private publisher _publisher;

        #endregion
        #region Association Fixup
    
        private void Fixupjob(job previousValue)
        {
            if (previousValue != null && previousValue.employees.Contains(this))
            {
                previousValue.employees.Remove(this);
            }
    
            if (job != null)
            {
                if (!job.employees.Contains(this))
                {
                    job.employees.Add(this);
                }
                if (jobid != job.id)
                {
                    jobid = job.id;
                }
            }
        }
    
        private void Fixuppublisher(publisher previousValue)
        {
            if (previousValue != null && previousValue.employees.Contains(this))
            {
                previousValue.employees.Remove(this);
            }
    
            if (publisher != null)
            {
                if (!publisher.employees.Contains(this))
                {
                    publisher.employees.Add(this);
                }
                if (publisherid != publisher.id)
                {
                    publisherid = publisher.id;
                }
            }
        }

        #endregion
    }
}
