//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Pubs.Data
{
    public partial class job
    {
        #region Primitive Properties
    
        public virtual short id
        {
            get;
            set;
        }
    
        public virtual string description
        {
            get;
            set;
        }
    
        public virtual byte minlevel
        {
            get;
            set;
        }
    
        public virtual byte maxlevel
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<employee> employees
        {
            get
            {
                if (_employees == null)
                {
                    var newCollection = new FixupCollection<employee>();
                    newCollection.CollectionChanged += Fixupemployees;
                    _employees = newCollection;
                }
                return _employees;
            }
            set
            {
                if (!ReferenceEquals(_employees, value))
                {
                    var previousValue = _employees as FixupCollection<employee>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupemployees;
                    }
                    _employees = value;
                    var newValue = value as FixupCollection<employee>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupemployees;
                    }
                }
            }
        }
        private ICollection<employee> _employees;

        #endregion
        #region Association Fixup
    
        private void Fixupemployees(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (employee item in e.NewItems)
                {
                    item.job = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (employee item in e.OldItems)
                {
                    if (ReferenceEquals(item.job, this))
                    {
                        item.job = null;
                    }
                }
            }
        }

        #endregion
    }
}
