//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace Pubs.Data
{
    public partial class pubsEntities : ObjectContext
    {
        public const string ConnectionString = "name=pubsEntities";
        public const string ContainerName = "pubsEntities";
    
        #region Constructors
    
        public pubsEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public pubsEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public pubsEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<author> authors
        {
            get { return _authors  ?? (_authors = CreateObjectSet<author>("authors")); }
        }
        private ObjectSet<author> _authors;
    
        public ObjectSet<employee> employees
        {
            get { return _employees  ?? (_employees = CreateObjectSet<employee>("employees")); }
        }
        private ObjectSet<employee> _employees;
    
        public ObjectSet<job> jobs
        {
            get { return _jobs  ?? (_jobs = CreateObjectSet<job>("jobs")); }
        }
        private ObjectSet<job> _jobs;
    
        public ObjectSet<publisher> publishers
        {
            get { return _publishers  ?? (_publishers = CreateObjectSet<publisher>("publishers")); }
        }
        private ObjectSet<publisher> _publishers;
    
        public ObjectSet<sale> sales
        {
            get { return _sales  ?? (_sales = CreateObjectSet<sale>("sales")); }
        }
        private ObjectSet<sale> _sales;
    
        public ObjectSet<store> stores
        {
            get { return _stores  ?? (_stores = CreateObjectSet<store>("stores")); }
        }
        private ObjectSet<store> _stores;
    
        public ObjectSet<titleauthor> titleauthors
        {
            get { return _titleauthors  ?? (_titleauthors = CreateObjectSet<titleauthor>("titleauthors")); }
        }
        private ObjectSet<titleauthor> _titleauthors;
    
        public ObjectSet<title> titles
        {
            get { return _titles  ?? (_titles = CreateObjectSet<title>("titles")); }
        }
        private ObjectSet<title> _titles;

        #endregion
    }
}
