//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Pubs.Data
{
    public partial class sale
    {
        #region Primitive Properties
    
        public virtual string storeid
        {
            get { return _storeid; }
            set
            {
                if (_storeid != value)
                {
                    if (store != null && store.id != value)
                    {
                        store = null;
                    }
                    _storeid = value;
                }
            }
        }
        private string _storeid;
    
        public virtual string ordernumber
        {
            get;
            set;
        }
    
        public virtual System.DateTime orderdate
        {
            get;
            set;
        }
    
        public virtual short quantity
        {
            get;
            set;
        }
    
        public virtual string paymentterms
        {
            get;
            set;
        }
    
        public virtual string titleid
        {
            get { return _titleid; }
            set
            {
                if (_titleid != value)
                {
                    if (title != null && title.id != value)
                    {
                        title = null;
                    }
                    _titleid = value;
                }
            }
        }
        private string _titleid;

        #endregion
        #region Navigation Properties
    
        public virtual store store
        {
            get { return _store; }
            set
            {
                if (!ReferenceEquals(_store, value))
                {
                    var previousValue = _store;
                    _store = value;
                    Fixupstore(previousValue);
                }
            }
        }
        private store _store;
    
        public virtual title title
        {
            get { return _title; }
            set
            {
                if (!ReferenceEquals(_title, value))
                {
                    var previousValue = _title;
                    _title = value;
                    Fixuptitle(previousValue);
                }
            }
        }
        private title _title;

        #endregion
        #region Association Fixup
    
        private void Fixupstore(store previousValue)
        {
            if (previousValue != null && previousValue.sales.Contains(this))
            {
                previousValue.sales.Remove(this);
            }
    
            if (store != null)
            {
                if (!store.sales.Contains(this))
                {
                    store.sales.Add(this);
                }
                if (storeid != store.id)
                {
                    storeid = store.id;
                }
            }
        }
    
        private void Fixuptitle(title previousValue)
        {
            if (previousValue != null && previousValue.sales.Contains(this))
            {
                previousValue.sales.Remove(this);
            }
    
            if (title != null)
            {
                if (!title.sales.Contains(this))
                {
                    title.sales.Add(this);
                }
                if (titleid != title.id)
                {
                    titleid = title.id;
                }
            }
        }

        #endregion
    }
}
