//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Pubs.Data
{
    public partial class store
    {
        #region Primitive Properties
    
        public virtual string id
        {
            get;
            set;
        }
    
        public virtual string name
        {
            get;
            set;
        }
    
        public virtual string address
        {
            get;
            set;
        }
    
        public virtual string city
        {
            get;
            set;
        }
    
        public virtual string state
        {
            get;
            set;
        }
    
        public virtual string zip
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<sale> sales
        {
            get
            {
                if (_sales == null)
                {
                    var newCollection = new FixupCollection<sale>();
                    newCollection.CollectionChanged += Fixupsales;
                    _sales = newCollection;
                }
                return _sales;
            }
            set
            {
                if (!ReferenceEquals(_sales, value))
                {
                    var previousValue = _sales as FixupCollection<sale>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupsales;
                    }
                    _sales = value;
                    var newValue = value as FixupCollection<sale>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupsales;
                    }
                }
            }
        }
        private ICollection<sale> _sales;

        #endregion
        #region Association Fixup
    
        private void Fixupsales(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (sale item in e.NewItems)
                {
                    item.store = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (sale item in e.OldItems)
                {
                    if (ReferenceEquals(item.store, this))
                    {
                        item.store = null;
                    }
                }
            }
        }

        #endregion
    }
}
