//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Pubs.Services.Entities
{
    public  class Employee
    {
        public string Id { get; set; }
        public string FirstName { get; set; }
//        public string Minit { get; set; }    
        public string LastName { get; set; }
        public short JobId { get; set; }
        public Nullable<byte> JobLevel { get; set; }
        public string PublisherId { get; set; }
        public DateTime HireDate { get; set; }
        public Publisher publisher { get; set; }
        public Job job { get; set; }
    }
}
