//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Pubs.Services.Entities
{
    public  class Title
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string PublisherId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Advance { get; set; }
        public Nullable<int> Royalty { get; set; }
        public Nullable<int> YTDSales { get; set; }
        public string Notes { get; set; }
        public DateTime PublishDate { get; set; }
       // public Publisher publisher { get; set; }
        public ICollection<Sale> sales { get; set; }
        public ICollection<TitleAuthor> titleauthors { get; set; }
    }
}
