//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Pubs.Web.Models
{
    public  class AuthorProjectionModel
    {
        public string Id { get; set; }
        public string AuthorName { get; set; }
        public string Phone { get; set; }
        public string City { get; set; }
        public string State { get; set; }
    }

}
