//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Pubs.Web.Models
{
    public  class SaleModel
    {
        public string StoreId { get; set; }
        public string OrderNumber { get; set; }
        public string OrderDate { get; set; }
        public short Quantity { get; set; }
        public string PaymentTerms { get; set; }
        public string TitleId { get; set; }
        public string StoreName { get; set; }   //flattening from store => Name
        public string StoreCity { get; set; }   //flattening from store => City
        public string TitleName { get; set; }   //flattening from Title => Name
    }
}
