//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Pubs.Services.Entities
{
    public  class TitleAuthor
    {
        public string AuthorId {get;set;}
        public string TitleId { get; set; }
        public Nullable<byte> AuthoreOrder { get; set; }
        public Nullable<int> RoyaltyPercent { get; set; }
        public Author author { get; set; }
        public Title  title { get; set; }
        
    }
}
